name: Backend CI

on:
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  quality:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Check formatting
        run: uv run ruff format --check .

      - name: Run linter
        run: uv run ruff check .

      - name: Run tests
        run: |
          cd core
          uv run python manage.py migrate
          uv run python manage.py test
