name: E2E Tests

on:
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Backend setup
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install backend dependencies
        run: cd backend && uv sync

      - name: Run migrations
        run: cd backend/core && uv run python manage.py migrate

      - name: Start backend server
        run: cd backend/core && uv run python manage.py runserver &

      # Frontend setup
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: cd frontend && npm ci

      - name: Build frontend
        run: cd frontend && npm run build

      - name: Start frontend server
        run: cd frontend && npm run preview -- --port 8080 &

      # Wait for servers to be ready
      - name: Wait for servers
        run: |
          echo "Waiting for backend..."
          timeout 60 bash -c 'until curl -s http://localhost:8000/api/products/ > /dev/null; do sleep 1; done'
          echo "Backend ready!"
          echo "Waiting for frontend..."
          timeout 60 bash -c 'until curl -s http://localhost:8080 > /dev/null; do sleep 1; done'
          echo "Frontend ready!"

      # Playwright setup and run
      - name: Install Playwright browsers
        run: cd frontend && npx playwright install chromium --with-deps

      - name: Run E2E tests
        run: cd frontend && npx playwright test
        env:
          CI: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 7
